server:
  port : 8081

spring:
  data:
    mongodb:
      url: mongodb://localhost:27017
      database: LoginDb


springdoc:
  api-docs:
    path: /api-docs    # http://localhost:8081/swagger-ui/index.html
